# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac1d69f0934f8555ef31ec939deea865cf72c681c5d4cb86e6567d013a15a188b5e08aab082fd2f9e477a7c0f089e9e3731626777bb77b6061475ee359ee04cc

test:
  secret_key_base: e013abf911f124a8c2ff7d51cf0398f7acb65fdee07360aab9408d5950f8d33ddbce708eeb21e5daa463dbbb590c0c370aaeb708dcb01996abb0f4fe8ded6447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
